### ISSUE TITLE
Possibility to show real times instead of gaps

### ISSUE THREAD

**Issue by jakoleh** [serek4/simhub-gaps-overlay#18]
Even, if the overlay name is gaps, I would prefer to see the opponents lap times instead of gaps in the display. Would it be possible to make it changeable with an event?

**Comment by serek4** [comment]
Done!
Still need to figure out how make it easy to change which is default.
And probably sync both screens to switch between gaps and lap times at the same time.
But you can use new version of overlay from [dev-issue18](https://github.com/serek4/simhub-gaps-overlay/tree/dev-issue18)  branch.
add button mapping for `GraphicalDashPlugin.actionA` in **SimHub** -> **Controls and events** to switch between lap times and deltas.
