### ISSUE TITLE
Full names

### ISSUE THREAD

**Issue by frankalexandre72** [serek4/simhub-gaps-overlay#23]
How can i make the dashboard use full name and not abreviation for fist name + last name?

**Comment by serek4** [comment]
In simhub **Dynleaderboards -> Dynamic leaderboards** chose gaps leaderboard and on the bottom in **properties for each driver** turn on FullName and restart simhub, than in `gaps-overlay-src.js` file in function driver_Name in line 45
change
```diff
  function driver_Name(position) {
    const teamName = /(\s*\|\s*.+)|(\s*\[.+\]\s*)$/;
-   return DynLeaderboardsPluginProp(leaderBoardName, position, "Driver.1.InitialPlusLastName").replace(teamName, "");
   }
```
to
```diff
  function driver_Name(position) {
    const teamName = /(\s*\|\s*.+)|(\s*\[.+\]\s*)$/;
+   return DynLeaderboardsPluginProp(leaderBoardName, position, "Driver.1.FullName").replace(teamName, "");
  }
```

**Comment by frankalexandre72** [comment]
It works. Thank you very much.
