### ISSUE TITLE
Mark players

### ISSUE THREAD

**Issue by VictorNarov** [serek4/simhub-gaps-overlay#25]
Hello, when racing against other drivers, it would be quite useful to mark some of your rivals to always keep an eye on their times, both for qualy and race, when they're not displayed on relative. 
Maybe on a separated page showing only selected drivers. Like a filter.

Also, it would be nice having a track map highlighting those marked players.

**Comment by serek4** [comment]
If i will ever try to do something like this it will be separate overlay, i prefer to keep this one as simple as possible to be easy to use while in race.
